#(c) 2024 Daniel DeMoney. All rights reserved.
services:
  jobrater:
    build:
      context: .
      dockerfile: Dockerfile  # Specify your Dockerfile
    image: jobrater-main
    env_file: .env  # Reference the .env file
    shm_size: '2g'
    ports:
      - "443:5001"   # Map port 80 on the host to port 5001 in the container
